[package]
name = "wasmsign2-rules-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wasmsign2-rules"
path = "src/cli/main.rs"

[dependencies]
clap = { version = "2.33.3", default-features = false, features = [
    "wrap_help",
] }
wasmsign2-rules = { version = "0.1.0", path = "src/lib" }
